name: build
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        architecture: [ 'x64' ]

    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Extension
        run: mvn install

      - name: Build Test Application
        run: mvn package && mvn clean package -f test/quarkus-test-app-xml/pom.xml -Pnative -Dnative-image.docker-build=true

      - name: Build the Docker Image
        run: cd test/quarkus-test-app-xml && docker build . -f Dockerfile.native -t hazelcast-guides/hazelcast-quarkus-native

      - name: Launch Application with Hazelcast Cluster
        run: cd test/quarkus-test-app-xml && docker-compose up -d

      - name: Verify
        run: |
          echo "Setting key=key_1&value=value_1"
          curl -s -X POST "localhost:8081/hazelcast/put?key=key_1&value=value_1" && sleep 1

          echo
          echo "Retrieving value for key=key_1"
          readonly result="$(curl "localhost:8080/hazelcast/get?key=key_1" | jq -r .value)"
          echo "Retrieved key_1 value: [$result]"
          [[ "$result" = "value_1" ]] || exit 1


